name: strap
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - captum=0.2.0=0
  - h5py=2.9.0=py36h7918eee_0
  - matplotlib=3.1.0=py36h5429711_0
  - numpy=1.18.1=py36h4f9e942_0
  - pandas=0.25.3=py36he6710b0_0
  - pillow=7.0.0=py36hb39fc2d_0
  - pip=19.3.1=py36_0
  - python=3.6.10=h0371630_0
  - pytorch=1.4.0=py3.6_cuda10.1.243_cudnn7.6.3_0
  - scipy=1.3.2=py36h7c811a0_0
  - torchvision=0.5.0=py36_cu101
  - pip:
    - histomicstk==1.0.3.dev56
    - scikit-learn==0.21.3
    - seaborn==0.11.0
    - tables==3.5.1
    - tqdm==4.41.1